name: Telegram API Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # запуск кожні 5 хвилин
  workflow_dispatch:       # дозволяє вручну запускати

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run monitor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python <<EOF
          import os
          import requests

          bot_token = os.getenv("BOT_TOKEN")
          chat_id = os.getenv("CHAT_ID")
          url = f"https://api.telegram.org/bot{bot_token}/getMe"
          alert_url = f"https://api.telegram.org/bot{bot_token}/sendMessage"

          try:
              r = requests.get(url, timeout=10)
              if r.status_code == 200:
                  print("API доступне")
              else:
                  requests.post(alert_url, data={
                      "chat_id": chat_id,
                      "text": f"⚠️ Telegram API недоступне (код {r.status_code})"
                  })
          except Exception as e:
              requests.post(alert_url, data={
                  "chat_id": chat_id,
                  "text": f"🚨 Telegram API не відповідає: {e}"
              })
          EOF
