name: Telegram API Monitor

on:
  schedule:
    - cron: "* * * * *"

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Create status file if missing
        run: |
          if [ ! -f status.txt ]; then
            echo "ok" > status.txt
          fi

      - name: Run monitor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python3 monitor.py

      - name: Save status
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add status.txt
          git commit -m "update status" || echo "No changes"
          git push || echo "No push permissions"
