name: Telegram API Monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Restore API status from cache
        id: cache-status
        uses: actions/cache@v4
        with:
          path: status.txt
          key: api-status

      - name: Create default status file if missing
        run: |
          if [ ! -f status.]()
